name: Auto-Update Playwright Version

on:
  schedule:
    # Run weekly on Mondays at 10 AM UTC
    - cron: '0 10 * * 1'
  workflow_dispatch:
    inputs:
      version:
        description: 'Playwright version to update to (leave empty for latest)'
        required: false
        type: string

jobs:
  update-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
    
    - name: Determine target version
      id: version
      run: |
        if [ -n "${{ github.event.inputs.version }}" ]; then
          TARGET_VERSION="${{ github.event.inputs.version }}"
        else
          TARGET_VERSION=$(npm view @playwright/test version)
        fi
        echo "target=$TARGET_VERSION" >> $GITHUB_OUTPUT
        echo "Target version: $TARGET_VERSION"
    
    - name: Update Dockerfile
      run: |
        # No need to update Dockerfile - it uses latest @playwright/test automatically
        echo "Dockerfile uses latest @playwright/test - no update needed"
    
    - name: Update README.md
      run: |
        sed -i "s/Playwright v[0-9.]*/Playwright v${{ steps.version.outputs.target }}/g" README.md
        echo "Updated README.md"
    
    - name: Update GitHub Actions workflow
      run: |
        # The docker-build.yml now dynamically detects the version, so no update needed
        echo "docker-build.yml uses dynamic version detection - no update needed"
    
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "Auto-update Playwright to v${{ steps.version.outputs.target }}"
        title: "Auto-update Playwright to v${{ steps.version.outputs.target }}"
        body: |
          ## Automated Playwright Version Update
          
          This PR automatically updates Playwright to v${{ steps.version.outputs.target }}.
          
          ### Files Updated
          - `README.md` - Updated version reference
          - `Dockerfile` uses latest version automatically
          
          ### Next Steps
          - [ ] Review changes
          - [ ] Test Docker build
          - [ ] Merge if everything looks good
          
          🤖 This PR was automatically created by the auto-update workflow.
        branch: auto-update-playwright-${{ steps.version.outputs.target }}
        base: main
        delete-branch: true