name: Check for New Playwright Version

on:
  schedule:
    # Run daily at 9 AM UTC
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  check-version:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
      packages: read
    
    steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
    
    - name: Get latest Playwright version
      id: latest-version
      run: |
        LATEST_VERSION=$(npm view @playwright/test version)
        echo "version=$LATEST_VERSION" >> $GITHUB_OUTPUT
        echo "Latest Playwright version: $LATEST_VERSION"
    
    - name: Check if image exists
      id: image-check
      run: |
        # Check if image with this version already exists using GitHub API
        IMAGE_EXISTS=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          "https://api.github.com/user/packages/container/${{ github.event.repository.name }}/versions" \
          | jq -r --arg version "${{ steps.latest-version.outputs.version }}" \
          '.[] | select(.metadata.container.tags[] == $version) | .id' | head -1)
        
        if [ -n "$IMAGE_EXISTS" ]; then
          echo "exists=true" >> $GITHUB_OUTPUT
          echo "Image for version ${{ steps.latest-version.outputs.version }} already exists"
        else
          echo "exists=false" >> $GITHUB_OUTPUT
          echo "Image for version ${{ steps.latest-version.outputs.version }} does not exist - build needed"
        fi
    
    - name: Trigger Docker build
      if: steps.image-check.outputs.exists == 'false'
      uses: actions/github-script@v7
      with:
        script: |
          await github.rest.actions.createWorkflowDispatch({
            owner: context.repo.owner,
            repo: context.repo.repo,
            workflow_id: 'docker-build.yml',
            ref: 'main'
          });
          
          console.log('Triggered Docker build for Playwright version ${{ steps.latest-version.outputs.version }}');